build:
  environment:
    php: 7.1.12
  nodes:
    analysis:
      image: default-bionic
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
    tests: true
