<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZfMailer\Module'                               => __DIR__ . '/Module.php',
    'ZfMailer\Options\ModuleOptions'                => __DIR__ . '/src/Options/ModuleOptions.php',
    'ZfMailer\Options\ModuleOptionsFactory'         => __DIR__ . '/src/Options/ModuleOptionsFactory.php',
    'ZfMailer\Service\AbstractMailer'               => __DIR__ . '/src/Service/AbstractMailer.php',
    'ZfMailer\Service\Mailer'                       => __DIR__ . '/src/Service/Mailer.php',
    'ZfMailer\Service\MailerFactory'                => __DIR__ . '/src/Service/MailerFactory.php',
    'ZfMailer\Service\MailMessageFactory'           => __DIR__ . '/src/Service/MailMessageFactory.php',
    'ZfMailer\Service\MailTransportFactory'         => __DIR__ . '/src/Service/MailTransportFactory.php',
    'ZfMailer\View\MailRendererFactory'             => __DIR__ . '/src/View/MailRendererFactory.php',
);
