<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'mail/default-html'     => __DIR__ . '/view/mail/default-html.phtml',
    'mail/default-text'     => __DIR__ . '/view/mail/default-text.phtml',
);
