<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'mail/sample-text-mail' => __DIR__ . '/view/mail/sample-text-mail.phtml',
    'mail/sample-html-mail' => __DIR__ . '/view/mail/sample-html-mail.phtml',
);
