# ZfMailer
# ---------------
# PHP CircleCI 2.0 configuration file
#
# Author:       Daniel Wolkenhauer <hello@dw-labs.de>
# Copyright:    (c) 2012 -2019 Daniel Wolkenhauer
# Home:         http://dw-labs.de
# Version:      1.0.0
# -----
# v.0.4

version: 2
jobs:
  build:
    working_directory: ~/dwolke/zf-mailer
    parallelism: 1
    shell: /bin/bash --login
    
    environment:
      CIRCLE_BRANCH: develop
    
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1.17-apache-stretch-node-browsers

    steps:
      - checkout

      # - run:
      #     name: Notwendige Tools installieren
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install -y libzip-dev
      #       sudo apt-get install -y zlib1g-dev libicu-dev g++

      - run:
          working_directory: ~/dwolke/zf-mailer
          command: 'echo ''Europe/Berlin'' | sudo tee -a /etc/timezone; sudo dpkg-reconfigure -f noninteractive tzdata;'      

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: Tests ausführen (PHPunit)
          command: |
            ./vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover=coverage.xml

      - run:
          name: Upload PHPunit results to codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -t 0c8021ca-d8a0-4b66-84b1-bd6cf7f43868
