<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
  <meta name="viewport" content="width=device-width">
  <meta name="format-detection" content="telephone=no">
  <style type="text/css">body{-webkit-text-size-adjust:none;-ms-text-size-adjust:none;font-weight:400;margin:0;padding:0;background-color:#f9f9f9}img{border:0;max-width:100%;height:auto;outline:none;display:inline-block;margin:0;padding:0;text-decoration:none;line-height:100%}@media screen and (max-width: 595px){body{padding:10px}.main{width:100%}.main .main-td{padding:20px}.header td{text-align:center}}</style>
</head>
<body bgcolor="f9f9f9">
  <p>&nbsp;</p>
  <table cellspacing="0" border="0" cellpadding="0" align="center" width="595" style="border-collapse:separate; border-spacing:0; table-layout:fixed; background-color:#fff; font-family:Helvetica, Arial, sans-serif; letter-spacing:0" bgcolor="#ffffff">
    <tbody>
      <tr>
        <td style="font-family:Helvetica, Arial, sans-serif; font-size:16px; padding:40px 60px; border:1px solid #ddd; border-radius:2px; box-shadow:0 1px 3px 0 rgba(0, 0, 0, 0.05)">
          <table width="100%" style="border-collapse:separate; border-spacing:0; table-layout:fixed">
          <tbody>
            <tr>
              <td style="font-family:Helvetica, Arial, sans-serif; font-size:15px; padding:0; color:#525252; line-height:22px">
                <h2 style="margin-top:30px; color:#282F33; font-size:18px; font-weight:bold; margin-bottom:7px">Das ist eine HTML E-Mail</h2>
                <p>Beispielvariable 1:&nbsp;<?php echo $this->Foo; ?></p>
                <p>Beispielvariable 2:&nbsp;<?php echo $this->Bar; ?></p>
                <p>Beispielvariable 3:&nbsp;<?php echo $this->Baz; ?></p>
                <p>&nbsp;</p>
                <p>Note: This template is intend for testing purpose only.</p>
              </td>
            </tr>
          </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
  <table width="100%" align="middle" style="border-collapse:separate; border-spacing:0; table-layout:fixed">
    <tbody>
      <tr>
        <td style="font-family:Helvetica, Arial, sans-serif; font-size:16px; padding:0">
          <table cellspacing="0" border="0" cellpadding="0" align="center" width="600" bgcolor="#f9f9f9" style="border-collapse:separate; border-spacing:0; table-layout:fixed; background-color:#f9f9f9; font-family:Helvetica, Arial, sans-serif; letter-spacing:0">
            <tbody>
              <tr>
                <td align="center" style="font-family:Helvetica, Arial, sans-serif; font-size:16px; padding:21px 30px 15px; text-align:center">
                  <p style="color:#b7b7b7; font-size:12px; font-weight:300; text-decoration:none; margin:0 0 6px 0">Made with ❤️ by dWolke</p>
                  <a href="#" style="border:none; color:#b7b7b7; font-size:12px; font-weight:300; text-decoration:none; outline:none">ZfMailer - Copyright © 2019. All rights reserved.</a>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>

</body>
</html>